# Generated by Django 3.1.1 on 2020-10-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='logo/'),
        ),
    ]
