# Generated by Django 3.1.1 on 2020-09-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Трансмиссия')),
            ],
            options={
                'verbose_name': 'Трасмиссия',
                'verbose_name_plural': 'Трансмисии',
            },
        ),
    ]
