# Generated by Django 3.1.2 on 2020-10-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='tel',
            field=models.CharField(max_length=150, verbose_name='Телефон'),
        ),
    ]
