# Generated by Django 3.1.1 on 2020-10-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0003_body_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('tel', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Название компании',
                'verbose_name_plural': 'Название компаний',
            },
        ),
    ]
