# Generated by Django 3.1.1 on 2020-10-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_blog', '0004_brend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
