version: '3.7'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/car
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=car_django
        - POSTGRES_PASSWORD=car_django
        - POSTGRES_DB=car_django_dev
    ports:
    - 5432:5432

volumes:
  postgres_data:
